Make mxcloud pipeline to retry when it fails

diff --git a/.github/workflows/mxcloud.yml b/.github/workflows/mxcloud.yml
--- a/.github/workflows/mxcloud.yml
+++ b/.github/workflows/mxcloud.yml
@@ -77,20 +77,33 @@ jobs:
         uses: tj-actions/branch-names@v6
       - name: Deploy to MxCloud
         shell: bash
-        run: >
-          curl --fail --location --max-time 120 --retry 5 --request POST '${{ secrets.MXCLOUD_URL }}/api/env/deploy'
-          --header 'Authorization: Basic ${{ secrets.MXCLOUD_AUTH }}'
-          --header 'Content-Type: application/json'
-          --data-raw '{
-          "git_project": "storefront-x",
-          "git_branch": "${{ steps.branch-name.outputs.current_branch }}",
-          "commit_ref": "${{ github.sha }}",
-          "env_vars": {
-          "DEPLOY_TYPE": "deploy",
-          "CI_REGISTRY": "${{ env.REGISTRY }}",
-          "CI_REPOSITORY_URL": "git@github.com:storefront-x/storefront-x.git",
-          "PROJECT_NAME": "storefront-x",
-          "BUILD_TAG": "${{ steps.branch-name.outputs.current_branch }}",
-          "CI_REPOSITORY": "${{ env.IMAGE_NAME }}"
-          }
-          }'
+        run: |
+          for i in $(seq 1 3); do
+            echo "Deploying '${{ steps.branch-name.outputs.current_branch }}' to ${{ secrets.MXCLOUD_URL }} attempt no. ${i}"
+            
+            curl --fail-with-body -L --max-time 120 --retry 5 --request POST '${{ secrets.MXCLOUD_URL }}/api/env/deploy' \
+              --header 'Authorization: Basic ${{ secrets.MXCLOUD_AUTH }}' \
+              --header 'Content-Type: application/json' \
+              --data-raw '{
+                "git_project": "storefront-x",
+                "git_branch": "${{ steps.branch-name.outputs.current_branch }}",
+                "commit_ref": "${{ github.sha }}",
+                "env_vars": {
+                  "DEPLOY_TYPE": "deploy",
+                  "CI_REGISTRY": "${{ env.REGISTRY }}",
+                  "CI_REPOSITORY_URL": "git@github.com:storefront-x/storefront-x.git",
+                  "PROJECT_NAME": "storefront-x",
+                  "BUILD_TAG": "${{ steps.branch-name.outputs.current_branch }}",
+                  "CI_REPOSITORY": "${{ env.IMAGE_NAME }}"
+                }
+              }' \
+              || (echo "Deploying request failed, retrying in 20 seconds ..." && sleep 20 && continue)
+            
+            ENV_DEPLOY_SUCCESS=true
+            break
+          done
+
+          if [ "$ENV_DEPLOY_SUCCESS" != true ]; then
+            echo "Deploy env request failed 3 times, exiting"
+            exit 1
+          fi
