Update

diff --git a/.github/workflows/mxcloud.yml b/.github/workflows/mxcloud.yml
--- a/.github/workflows/mxcloud.yml
+++ b/.github/workflows/mxcloud.yml
@@ -17,7 +17,7 @@ env:
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
-  build-and-push-image:
+  mxcloud:
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -50,20 +50,35 @@ jobs:
           build-args: SFX_CONFIG=${{ inputs.storefront-x-config }}
 
       - name: Deploy to MxCloud
+        shell: bash
         run: >
-          curl -L --max-time 120 --retry 5 --request POST ${{ secrets.MXCLOUD_URL }}/api/env/deploy
-          --header 'Authorization: Basic ${{ secrets.MXCLOUD_AUTH }}'
-          --header 'Content-Type: application/json'
-          --data-raw '{
-          "git_project": "storefront-x",
-          "git_branch": "${{ github.ref_name }}",
-          "commit_ref": "${{ github.sha }}",
-          "env_vars": {
-          "DEPLOY_TYPE": "deploy",
-          "CI_REGISTRY": "${{ env.REGISTRY }}",
-          "CI_REPOSITORY_URL": "git@github.com:storefront-x/storefront-x.git",
-          "PROJECT_NAME": "storefront-x",
-          "BUILD_TAG": "${{ github.ref_name }}",
-          "CI_REPOSITORY": "${{ env.IMAGE_NAME }}"
-          }
-          }'
+          ENV_DEPLOY_SUCCESS=false
+
+          for i in $(seq 1 3); do
+            echo "Deploying '$BUILD_TAG' to $MXCLOUD_DEPLOY_API_DOMAIN attemp no. ${i}"
+
+            curl --fail-with-body -L --max-time 120 --retry 5 --request POST ${{ secrets.MXCLOUD_URL }}/api/env/deploy
+            --header 'Authorization: Basic ${{ secrets.MXCLOUD_AUTH }}'
+            --header 'Content-Type: application/json'
+            --data-raw '{
+            "git_project": "storefront-x",
+            "git_branch": "${{ github.ref_name }}",
+            "commit_ref": "${{ github.sha }}",
+            "env_vars": {
+            "DEPLOY_TYPE": "deploy",
+            "CI_REGISTRY": "${{ env.REGISTRY }}",
+            "CI_REPOSITORY_URL": "git@github.com:storefront-x/storefront-x.git",
+            "PROJECT_NAME": "storefront-x",
+            "BUILD_TAG": "${{ github.ref_name }}",
+            "CI_REPOSITORY": "${{ env.IMAGE_NAME }}"
+            }
+            }' || (echo "Deploying request failed, retrying in 20 seconds ..." && sleep 20 && continue)
+
+            ENV_DEPLOY_SUCCESS=true
+            break
+          done
+
+          if [ "$ENV_DEPLOY_SUCCESS" = false ]; then
+            echo "Deploy env request failed 3 times, exiting"
+            exit 1
+          fi
